spring:
  application:
    name: spring-cloud-config
  profiles:
    active: native
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9092
    topic:
      name: microservices
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
