spring:
  application:
    name: open-ai
  ai:
    openai:
      api-key: <your api key>
      chat:
        options:
          model: gpt-4o
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/rag
    username: postgres
    password: postgres
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
server:
  port: 9300
springdoc:
  swagger-ui:
    groups-order: asc
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    filter: ""
    path: /
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
management:
  endpoints:
    web:
      exposure:
        include: '*'
