spring:
  application:
    name: report
  kafka:
    topic:
      name: microservices
    producer:
      bootstrap-servers:
        - localhost:9092
      group-id: myGroup
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  ai:
    openai:
      api-key: <your api key>
      chat:
        options:
          model: gpt-4o
server:
  port: 9200
springdoc:
  swagger-ui:
    groups-order: asc
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    filter: ""
    path: /
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
management:
  endpoints:
    web:
      exposure:
        include: '*'
